# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 01631f9332bf863ca40b38f16442d3a85440ad413f54bcad30211c506e5b05e9971547c808477a247103ea502a9a5e828f1f97d598955f2bdc18e45ee228e681

test:
  secret_key_base: 7915f18007adf4d7a889696cd9e93b56263f5b12e9d70b373e85ce30ad3ded002d33c87ed6473da689ea94d2af4fdfa0554c1373ded4b1203b690dfdbf7b4642

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
